name: 功能建议
description: 为本项目提出新功能或改进建议
title: "[功能]: "
labels: ["enhancement"]
assignees:
  - saicaca
body:
  - type: markdown
    attributes:
      value: |
        感谢你抽出时间填写功能建议！
  - type: textarea
    id: related-problem
    attributes:
      label: 该功能建议是否与某个问题相关？
      description: 请清晰、简洁地描述当前存在的问题。例如：我总是在 [...] 时感到困扰。
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 你希望的解决方案
      description: 请清晰、简洁地描述你希望实现的功能或行为。
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 你考虑过的替代方案
      description: 请描述你考虑过的其他解决方案或功能方案。
  - type: textarea
    id: additional-context
    attributes:
      label: 补充信息
      description: 可在此补充其他上下文信息或截图。
  - type: markdown
    attributes:
      value: |
        **说明**

        功能是否采纳与何时实现由仓库维护者 @saicaca 决定，无法保证一定会实现。
